require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - '.bundle/**/*'
    - '.git/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'config/routes.rb'
  NewCops: enable
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.6

#################### Layout ###########################

Layout/ClassStructure:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle:
    - key
    - table
  EnforcedHashRocketStyle:
    - key
    - table

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/IndentationConsistency:
  Severity: error

Layout/IndentationWidth:
  Severity: error

Layout/LineLength:
  Max: 83

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/TrailingWhitespace:
  Severity: error

#################### Metrics ###########################

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb # nearly all spec files go over 25 lines

#################### Rails & RSpec ###########################

Rails/Output:
  Exclude:
    - db/seeds/**/*.rb

Rails/SkipsModelValidations:
  AllowedMethods:
    - update_all

Rails/UniqBeforePluck:
  AutoCorrect: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging

RSpec/InstanceVariable:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Max: 25 # 5 was too idealistic

RSpec/MultipleExpectations:
  Max: 10 # 1 was too idealistic

#################### Style ###########################

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets
